In [6]:
import numpy as np
import pandas as pd
import subprocess
import argparse
from IPython.display import display

In [11]:
def mat(n_nodes=20):
    """
        This function computes the matrix from node number 

        Args :
        n_nodes : Number of nodes

        Returns:
        M : matrix (NxN) with N = 2 pow of the number of bits of n_nodes

    """
    bit_length = n_nodes.bit_length() # retrieving the number of bits needed to encode the number
    N = 2 ** bit_length # retrieving the size of the square matrix
    M = np.array([[np.nan]*N]*N) # initializing the matrix with nan of size 32*32
    #print(M.shape) # verification

    Na = N # address number

    for destination in range(Na):
        for source in range(Na):
            if source == destination or source ==0 or destination==0 or source == Na-1:
                continue
            if source > destination:
                M[destination][source] = destination*(Na-2) + (source-1)
            else:
                M[destination][source] = destination*(Na-2) + source
    
    return M

def get_probs(mat,network_mode=0):
    """
        This function computes the probability matrix

        Args :
        mat : matrix from number of nodes

        Returns:
        P : probability matrix of symbols
        P_symbols : one dimensional array containing each symbol's probability

    """
    # end getting symbols
    
    is_mixed = True if network_mode == 2 else False
    is_autonomous = True if network_mode==0 else False
    # start variable initialization
    P = np.zeros(mat.shape)
    N = len(mat)
    #P_symbols = np.zeros(2**N)
    Na = N
    Na2 = Na**2
    a_gate = 1
    p0 = (Na-2)**-1
    p1 = (Na-3)**-1
    p2 = (Na2 - 6*Na + 9)**-1
    # end variable initialization

    for destination in range(N):
        for source in range(N):
            gamma_a = 1
            gamma_c = 0 if is_autonomous else 1

            if is_mixed:
                gamma_a = 0.9
                gamma_c = 0.5
            if np.isnan(mat[destination,source]):
                P[destination,source] = np.nan
                continue
            if source==a_gate:
                p = (1-gamma_a)*p0
            elif destination == a_gate:
                p = (gamma_a-gamma_c)*p1
            elif source!=a_gate and destination!=a_gate:
                #gamma_a=gamma_c=1
                p = (gamma_c)*p2
            P[destination,source] = p
            #P_symbols[int(mat[destination,source])] = p
    return P#,P_symbols

#https://stackoverflow.com/questions/11587044/how-can-i-create-a-tree-for-huffman-encoding-and-decoding

def get_symbols(P):
    """
        Get symbols from P
    """
    # start getting symbols
    P[np.isnan(P)] = -1
    symbols = list(set(list(P.flatten())))
    symbols.remove(-1)
    return symbols

def get_occurence(M):
    """
        Get occurences from P
    """
    sym = get_symbols(M)
    T = []
    M = M.flatten()
    for i in sym:
        T.append(np.count_nonzero(M == i))
    return T,sym

def get_entropy(codes):
    probs = [i for i in codes.values()]
    entropy = sum([(np.log2(1/pi)*pi) for pi in probs])
    return entropy
def assign_code(nodes, label, result, prefix = ''):
    """
        assigning code to each nodes of the tree
    """    
    childs = nodes[label]     
    tree = {}
    if len(childs) == 2:
        tree['0'] = assign_code(nodes, childs[0], result, prefix+'0')
        tree['1'] = assign_code(nodes, childs[1], result, prefix+'1')     
        return tree
    else:
        result[label] = prefix
        return label

def Huffman_code(_vals): 
    """
        Computing the code with Huffman from the frequence probs

        Args:
            _vals : frequence matrix
        Returns:
            tree : the resulting tree 
            code : tree with code

    """   
    vals = _vals.copy()
    nodes = {}
    for n in vals.keys(): # leafs initialization
        nodes[n] = []

    while len(vals) > 1: # binary tree creation
        s_vals = sorted(vals.items(), key=lambda x:x[1]) 
        a1 = s_vals[0][0]
        a2 = s_vals[1][0]
        vals[a1+a2] = vals.pop(a1) + vals.pop(a2)
        nodes[a1+a2] = [a1, a2]        
    code = {}
    root = a1+a2
    tree = {}
    tree = assign_code(nodes, root, code)   # assignment of the code for the given binary tree      
    return code, tree

def decode_(encoded,tree):
    """
        Decode an encode input using the tree
    """
    decoded = []
    i = 0
    while i < len(encoded): # decoding using the binary graph
        ch = encoded[i]  
        act = tree[ch]
        while not isinstance(act, str):
            i += 1
            ch = encoded[i]  
            act = act[ch]        
        decoded.append(act)          
        i += 1
    return decoded

def encode_(plain,code):
    """
        Encode an input from a raw input
    """
    return ''.join([code[t] for t in plain])

def draw_tree(tree, prefix = ''): 
    """ 
        Draw tree from the computed  into a format undestandable by the grapviz dot
    """   
    if isinstance(tree, str):            
        descr = 'N%s [label="%s:%s", fontcolor=blue, fontsize=16, width=2, shape=box];\n'%(prefix, tree, prefix)
    else: # Node description
        descr = 'N%s [label="%s"];\n'%(prefix, prefix)
        for child in tree.keys():
            descr += draw_tree(tree[child], prefix = prefix+child)
            descr += 'N%s -> N%s;\n'%(prefix,prefix+child)
    return descr

def export_graph(tree,filename="graph.png"):

    """
        Export tree as a png image file from the formatted tree
    """

    with open('graph.dot','w') as f:
        f.write('digraph G {\n')
        f.write(draw_tree(tree))
        f.write('}') 
    subprocess.call('dot -Tpng graph.dot -o {}'.format(filename), shell=True)

def make_freq(P):
    """
        Make the frequence list of tuples (key: value)
    """
    P_tups = []
    for destination in range(len(P)):
        for source in range(len(P)):
            if np.isnan(P[destination,source]) or P[destination,source]==0:
                continue
            P_tups.append([P[destination,source], "{}-{}".format(destination,source)])
    return P_tups

def get_bits(raw):
    """
        Helper function to undo the tree formatting to get only bits (for countring puposes)
    """
    return raw.split(',')[0].split('=')[1].replace('"','').split(':')[1]

def sum_up_one(P):
    """
        Transform an array of probs to sum up to 1
    """
    P [np.isnan(P)] = 0.0
    Pt = []
    for id,i in enumerate(P):
        if sum(i)>0:
            Pt.append(i/sum(i))
        else:
            Pt.append(i)
    Pt = np.array(Pt).T
    Pt[Pt==0] = np.nan
    return Pt
def plot_mat(M,outpath=None,is_prob=False,network_mode=0):
    is_mixed = True if network_mode == 2 else False
    is_autonomous = True if network_mode==0 else False

    df = pd.DataFrame(M, columns=[str(i) for i in range(M.shape[1])])
    if outpath:
        if not is_mixed:
            df.to_csv(outpath+"/Matrix_{}_{}.csv".format("prob" if is_prob else "matrix","autonomous" if is_autonomous else "collaborative"))
        else:
            df.to_csv(outpath+"/Matrix_{}_{}.csv".format("prob" if is_prob else "matrix","mixed"))
    display(df)

def get_bin_codes(vals):
    bits = len(vals).bit_length()
    rets = vals.copy()
    for i,k in enumerate(vals.keys()):
        rets[k] = np.binary_repr(i, width=bits)    
    return rets



def main(n_nodes=6,network_mode=3,outpath="graph.png",verbose=False):
    """
        Executes the whole program from users input parameters
    """

    print("Computing with n_nodes : {} \n".format(n_nodes))

    M = mat(n_nodes)
    P = get_probs(M,network_mode)#[0]
    
    #P_old = P.copy()

    #P = sum_up_one(P)
    freq = make_freq(P)
    #print(freq)
    vals = {l:v for (v,l) in freq}
    #print(vals)
    codes, tree = Huffman_code(vals)
    #codes = get_bin_codes(vals) if len(list(set(vals.values())))==1 else code
    #if autonomous:

    #print(tree)

    t = draw_tree(tree).split("\n")
    #print(t) n_bits/(((2**(n_nodes.bit_length()))-1)**2)
    #tx = [ get_bits(i) for i in t if "fontcolor=blue" in i]
    #n_bits = np.sum(np.array([len(i) for i in tx]))
    n_bits =sum( [ len(k) for k in codes.values()])
    
    code_length = sum([ len(codes[k])*vals[k] for k in vals.keys()])


    if verbose:
        print("*"*20,"\n Matrix : \n ", "*"*20)
        plot_mat(M,outpath,is_prob=False,network_mode=network_mode)
        print("\n\n")

        print("*"*20,"\n Probabilities  : \n ", "*"*20)
        plot_mat(np.round_(P, decimals = 4),outpath,is_prob=True,network_mode=network_mode)
        print("\n\n")

        print("*"*20,"\n Huffman tree : \n ", "*"*20)
        print(tree)
        #print(t)
        print("\n\n")

        print("*"*20,"\n Code dictionary : \n ", "*"*20)
        print(codes)
        print("\n\n")

    if outpath:
        export_graph(tree,filename=outpath+"/graph.png")
    print("Leaf number : {}".format(len(t)))
    print("Huffman code : {}".format(n_bits))
    print("Entropy : {}".format(get_entropy(vals)))
    print("Huffman Code length : {} ".format(code_length))

#### Autonomous Network

In [31]:
main(8,network_mode=0,outpath="C:\\Users\\emman\\Documents\\resultats",verbose=True)

Computing with n_nodes : 8

********************
 Matrix :
  ********************

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,NaN
2,NaN,29.0,NaN,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,NaN
3,NaN,43.0,44.0,NaN,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,NaN
4,NaN,57.0,58.0,59.0,NaN,60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,NaN
5,NaN,71.0,72.0,73.0,74.0,NaN,75.0,76.0,77.0,78.0,79.0,80.0,81.0,82.0,83.0,NaN
6,NaN,85.0,86.0,87.0,88.0,89.0,NaN,90.0,91.0,92.0,93.0,94.0,95.0,96.0,97.0,NaN
7,NaN,99.0,100.0,101.0,102.0,103.0,104.0,NaN,105.0,106.0,107.0,108.0,109.0,110.0,111.0,NaN
8,NaN,113.0,114.0,115.0,116.0,117.0,118.0,119.0,NaN,120.0,121.0,122.0,123.0,124.0,125.0,NaN
9,NaN,127.0,128.0,129.0,130.0,131.0,132.0,133.0,134.0,NaN,135.0,136.0,137.0,138.0,139.0,NaN
10,NaN,141.0,142.0,143.0,144.0,145.0,146.0,147.0,148.0,149.0,NaN,150.0,151.0,152.0,153.0,NaN
11,NaN,155.0,156.0,157.0,158.0,159.0,160.0,161.0,162.0,163.0,164.0,NaN,165.0,166.0,167.0,NaN
12,NaN,169.0,170.0,171.0,172.0,173.0,174.0,175.0,176.0,177.0,178.0,179.0,NaN,180.0,181.0,NaN
13,NaN,183.0,184.0,185.0,186.0,187.0,188.0,189.0,190.0,191.0,192.0,193.0,194.0,NaN,195.0,NaN
14,NaN,197.0,198.0,199.0,200.0,201.0,202.0,203.0,204.0,205.0,206.0,207.0,208.0,209.0,NaN,NaN
15,NaN,211.0,212.0,213.0,214.0,215.0,216.0,217.0,218.0,219.0,220.0,221.0,222.0,223.0,224.0,NaN

********************
 Probabilities  :
  ********************

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0.0769,0.0769,0.0769,0.0769,0.0769,0.0769,0.0769,0.0769,0.0769,0.0769,0.0769,0.0769,0.0769,NaN
2,NaN,0.0,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN
3,NaN,0.0,0.0000,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN
4,NaN,0.0,0.0000,0.0000,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN
5,NaN,0.0,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN
6,NaN,0.0,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN
7,NaN,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN
8,NaN,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN
9,NaN,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,NaN
10,NaN,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,0.0000,0.0000,NaN
11,NaN,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,0.0000,NaN
12,NaN,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,0.0000,NaN
13,NaN,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,0.0000,NaN
14,NaN,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN,NaN
15,NaN,0.0,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN

********************
 Huffman tree :
  ********************
{'0': {'0': {'0': '1-12', '1': '1-13'}, '1': {'0': '1-14', '1': {'0': '1-2', '1': '1-3'}}}, '1': {'0': {'0': {'0': '1-4', '1': '1-5'}, '1': {'0': '1-6', '1': '1-7'}}, '1': {'0': {'0': '1-8', '1': '1-9'}, '1': {'0': '1-10', '1': '1-11'}}}}



********************
 Code dictionary :
  ********************
{'1-12': '000', '1-13': '001', '1-14': '010', '1-2': '0110', '1-3': '0111', '1-4': '1000', '1-5': '1001', '1-6': '1010', '1-7': '1011', '1-8': '1100', '1-9': '1101', '1-10': '1110', '1-11': '1111'}



Leaf number : 50
Huffman code : 49
Entropy : 3.7004397181410926
Huffman Code length : 3.769230769230769

### Collaborative Network

In [37]:
main(8,network_mode=1,outpath="C:\\Users\\emman\\Documents\\resultats",verbose=True)

Computing with n_nodes : 8

********************
 Matrix :
  ********************

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,NaN
2,NaN,29.0,NaN,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,NaN
3,NaN,43.0,44.0,NaN,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,NaN
4,NaN,57.0,58.0,59.0,NaN,60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,NaN
5,NaN,71.0,72.0,73.0,74.0,NaN,75.0,76.0,77.0,78.0,79.0,80.0,81.0,82.0,83.0,NaN
6,NaN,85.0,86.0,87.0,88.0,89.0,NaN,90.0,91.0,92.0,93.0,94.0,95.0,96.0,97.0,NaN
7,NaN,99.0,100.0,101.0,102.0,103.0,104.0,NaN,105.0,106.0,107.0,108.0,109.0,110.0,111.0,NaN
8,NaN,113.0,114.0,115.0,116.0,117.0,118.0,119.0,NaN,120.0,121.0,122.0,123.0,124.0,125.0,NaN
9,NaN,127.0,128.0,129.0,130.0,131.0,132.0,133.0,134.0,NaN,135.0,136.0,137.0,138.0,139.0,NaN
10,NaN,141.0,142.0,143.0,144.0,145.0,146.0,147.0,148.0,149.0,NaN,150.0,151.0,152.0,153.0,NaN
11,NaN,155.0,156.0,157.0,158.0,159.0,160.0,161.0,162.0,163.0,164.0,NaN,165.0,166.0,167.0,NaN
12,NaN,169.0,170.0,171.0,172.0,173.0,174.0,175.0,176.0,177.0,178.0,179.0,NaN,180.0,181.0,NaN
13,NaN,183.0,184.0,185.0,186.0,187.0,188.0,189.0,190.0,191.0,192.0,193.0,194.0,NaN,195.0,NaN
14,NaN,197.0,198.0,199.0,200.0,201.0,202.0,203.0,204.0,205.0,206.0,207.0,208.0,209.0,NaN,NaN
15,NaN,211.0,212.0,213.0,214.0,215.0,216.0,217.0,218.0,219.0,220.0,221.0,222.0,223.0,224.0,NaN

********************
 Probabilities  :
  ********************

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,NaN
2,NaN,0.0,NaN,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN
3,NaN,0.0,0.0059,NaN,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN
4,NaN,0.0,0.0059,0.0059,NaN,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN
5,NaN,0.0,0.0059,0.0059,0.0059,NaN,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN
6,NaN,0.0,0.0059,0.0059,0.0059,0.0059,NaN,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN
7,NaN,0.0,0.0059,0.0059,0.0059,0.0059,0.0059,NaN,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN
8,NaN,0.0,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN
9,NaN,0.0,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN,0.0059,0.0059,0.0059,0.0059,0.0059,NaN
10,NaN,0.0,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN,0.0059,0.0059,0.0059,0.0059,NaN
11,NaN,0.0,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN,0.0059,0.0059,0.0059,NaN
12,NaN,0.0,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN,0.0059,0.0059,NaN
13,NaN,0.0,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN,0.0059,NaN
14,NaN,0.0,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN,NaN
15,NaN,0.0,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,0.0059,NaN

********************
 Huffman tree :
  ********************
{'0': {'0': {'0': {'0': {'0': {'0': {'0': '8-13', '1': '8-14'}, '1': {'0': '9-2', '1': '9-3'}}, '1': {'0': {'0': '9-4', '1': '9-5'}, '1': {'0': '9-6', '1': '9-7'}}}, '1': {'0': {'0': {'0': '9-8', '1': '9-10'}, '1': {'0': '9-11', '1': '9-12'}}, '1': {'0': {'0': '9-13', '1': '9-14'}, '1': {'0': '10-2', '1': '10-3'}}}}, '1': {'0': {'0': {'0': {'0': '10-4', '1': '10-5'}, '1': {'0': '10-6', '1': '10-7'}}, '1': {'0': {'0': '10-8', '1': '10-9'}, '1': {'0': '10-11', '1': '10-12'}}}, '1': {'0': {'0': {'0': '10-13', '1': '10-14'}, '1': {'0': '11-2', '1': '11-3'}}, '1': {'0': {'0': '11-4', '1': '11-5'}, '1': {'0': '11-6', '1': '11-7'}}}}}, '1': {'0': {'0': {'0': {'0': {'0': '11-8', '1': '11-9'}, '1': {'0': '11-10', '1': '11-12'}}, '1': {'0': {'0': '11-13', '1': '11-14'}, '1': {'0': '12-2', '1': '12-3'}}}, '1': {'0': {'0': {'0': '12-4', '1': '12-5'}, '1': {'0': '12-6', '1': '12-7'}}, '1': {'0': {'0': '12-8', '1': '12-9'}, '1': {'0': '12-10', '1': '12-11'}}}}, '1': {'0': {'0': {'0': {'0': '12-13', '1': '12-14'}, '1': {'0': '13-2', '1': '13-3'}}, '1': {'0': {'0': '13-4', '1': '13-5'}, '1': {'0': '13-6', '1': '13-7'}}}, '1': {'0': {'0': {'0': '13-8', '1': '13-9'}, '1': {'0': '13-10', '1': '13-11'}}, '1': {'0': {'0': '13-12', '1': '13-14'}, '1': {'0': '14-2', '1': '14-3'}}}}}}, '1': {'0': {'0': {'0': {'0': {'0': {'0': '14-4', '1': '14-5'}, '1': {'0': '14-6', '1': '14-7'}}, '1': {'0': {'0': '14-8', '1': '14-9'}, '1': {'0': '14-10', '1': '14-11'}}}, '1': {'0': {'0': {'0': '14-12', '1': '14-13'}, '1': {'0': '15-2', '1': '15-3'}}, '1': {'0': {'0': '15-4', '1': '15-5'}, '1': {'0': '15-6', '1': '15-7'}}}}, '1': {'0': {'0': {'0': {'0': '15-8', '1': '15-9'}, '1': {'0': '15-10', '1': '15-11'}}, '1': {'0': {'0': '15-12', '1': '15-13'}, '1': {'0': '15-14', '1': {'0': '2-3', '1': '2-4'}}}}, '1': {'0': {'0': {'0': {'0': '2-5', '1': '2-6'}, '1': {'0': '2-7', '1': '2-8'}}, '1': {'0': {'0': '2-9', '1': '2-10'}, '1': {'0': '2-11', '1': '2-12'}}}, '1': {'0': {'0': {'0': '2-13', '1': '2-14'}, '1': {'0': '3-2', '1': '3-4'}}, '1': {'0': {'0': '3-5', '1': '3-6'}, '1': {'0': '3-7', '1': '3-8'}}}}}}, '1': {'0': {'0': {'0': {'0': {'0': {'0': '3-9', '1': '3-10'}, '1': {'0': '3-11', '1': '3-12'}}, '1': {'0': {'0': '3-13', '1': '3-14'}, '1': {'0': '4-2', '1': '4-3'}}}, '1': {'0': {'0': {'0': '4-5', '1': '4-6'}, '1': {'0': '4-7', '1': '4-8'}}, '1': {'0': {'0': '4-9', '1': '4-10'}, '1': {'0': '4-11', '1': '4-12'}}}}, '1': {'0': {'0': {'0': {'0': '4-13', '1': '4-14'}, '1': {'0': '5-2', '1': '5-3'}}, '1': {'0': {'0': '5-4', '1': '5-6'}, '1': {'0': '5-7', '1': '5-8'}}}, '1': {'0': {'0': {'0': '5-9', '1': '5-10'}, '1': {'0': '5-11', '1': '5-12'}}, '1': {'0': {'0': '5-13', '1': '5-14'}, '1': {'0': '6-2', '1': '6-3'}}}}}, '1': {'0': {'0': {'0': {'0': {'0': '6-4', '1': '6-5'}, '1': {'0': '6-7', '1': '6-8'}}, '1': {'0': {'0': '6-9', '1': '6-10'}, '1': {'0': '6-11', '1': '6-12'}}}, '1': {'0': {'0': {'0': '6-13', '1': '6-14'}, '1': {'0': '7-2', '1': '7-3'}}, '1': {'0': {'0': '7-4', '1': '7-5'}, '1': {'0': '7-6', '1': '7-8'}}}}, '1': {'0': {'0': {'0': {'0': '7-9', '1': '7-10'}, '1': {'0': '7-11', '1': '7-12'}}, '1': {'0': {'0': '7-13', '1': '7-14'}, '1': {'0': '8-2', '1': '8-3'}}}, '1': {'0': {'0': {'0': '8-4', '1': '8-5'}, '1': {'0': '8-6', '1': '8-7'}}, '1': {'0': {'0': '8-9', '1': '8-10'}, '1': {'0': '8-11', '1': '8-12'}}}}}}}}



********************
 Code dictionary :
  ********************
{'8-13': '0000000', '8-14': '0000001', '9-2': '0000010', '9-3': '0000011', '9-4': '0000100', '9-5': '0000101', '9-6': '0000110', '9-7': '0000111', '9-8': '0001000', '9-10': '0001001', '9-11': '0001010', '9-12': '0001011', '9-13': '0001100', '9-14': '0001101', '10-2': '0001110', '10-3': '0001111', '10-4': '0010000', '10-5': '0010001', '10-6': '0010010', '10-7': '0010011', '10-8': '0010100', '10-9': '0010101', '10-11': '0010110', '10-12': '0010111', '10-13': '0011000', '10-14': '0011001', '11-2': '0011010', '11-3': '0011011', '11-4': '0011100', '11-5': '0011101', '11-6': '0011110', '11-7': '0011111', '11-8': '0100000', '11-9': '0100001', '11-10': '0100010', '11-12': '0100011', '11-13': '0100100', '11-14': '0100101', '12-2': '0100110', '12-3': '0100111', '12-4': '0101000', '12-5': '0101001', '12-6': '0101010', '12-7': '0101011', '12-8': '0101100', '12-9': '0101101', '12-10': '0101110', '12-11': '0101111', '12-13': '0110000', '12-14': '0110001', '13-2': '0110010', '13-3': '0110011', '13-4': '0110100', '13-5': '0110101', '13-6': '0110110', '13-7': '0110111', '13-8': '0111000', '13-9': '0111001', '13-10': '0111010', '13-11': '0111011', '13-12': '0111100', '13-14': '0111101', '14-2': '0111110', '14-3': '0111111', '14-4': '1000000', '14-5': '1000001', '14-6': '1000010', '14-7': '1000011', '14-8': '1000100', '14-9': '1000101', '14-10': '1000110', '14-11': '1000111', '14-12': '1001000', '14-13': '1001001', '15-2': '1001010', '15-3': '1001011', '15-4': '1001100', '15-5': '1001101', '15-6': '1001110', '15-7': '1001111', '15-8': '1010000', '15-9': '1010001', '15-10': '1010010', '15-11': '1010011', '15-12': '1010100', '15-13': '1010101', '15-14': '1010110', '2-3': '10101110', '2-4': '10101111', '2-5': '10110000', '2-6': '10110001', '2-7': '10110010', '2-8': '10110011', '2-9': '10110100', '2-10': '10110101', '2-11': '10110110', '2-12': '10110111', '2-13': '10111000', '2-14': '10111001', '3-2': '10111010', '3-4': '10111011', '3-5': '10111100', '3-6': '10111101', '3-7': '10111110', '3-8': '10111111', '3-9': '11000000', '3-10': '11000001', '3-11': '11000010', '3-12': '11000011', '3-13': '11000100', '3-14': '11000101', '4-2': '11000110', '4-3': '11000111', '4-5': '11001000', '4-6': '11001001', '4-7': '11001010', '4-8': '11001011', '4-9': '11001100', '4-10': '11001101', '4-11': '11001110', '4-12': '11001111', '4-13': '11010000', '4-14': '11010001', '5-2': '11010010', '5-3': '11010011', '5-4': '11010100', '5-6': '11010101', '5-7': '11010110', '5-8': '11010111', '5-9': '11011000', '5-10': '11011001', '5-11': '11011010', '5-12': '11011011', '5-13': '11011100', '5-14': '11011101', '6-2': '11011110', '6-3': '11011111', '6-4': '11100000', '6-5': '11100001', '6-7': '11100010', '6-8': '11100011', '6-9': '11100100', '6-10': '11100101', '6-11': '11100110', '6-12': '11100111', '6-13': '11101000', '6-14': '11101001', '7-2': '11101010', '7-3': '11101011', '7-4': '11101100', '7-5': '11101101', '7-6': '11101110', '7-8': '11101111', '7-9': '11110000', '7-10': '11110001', '7-11': '11110010', '7-12': '11110011', '7-13': '11110100', '7-14': '11110101', '8-2': '11110110', '8-3': '11110111', '8-4': '11111000', '8-5': '11111001', '8-6': '11111010', '8-7': '11111011', '8-9': '11111100', '8-10': '11111101', '8-11': '11111110', '8-12': '11111111'}



Leaf number : 674
Huffman code : 1265
Entropy : 7.400879436282176
Huffman Code length : 7.485207100591708

### Mixed network

In [36]:
main(8,network_mode=2,outpath="C:\\Users\\emman\\Documents\\resultats",verbose=True)

Computing with n_nodes : 8

********************
 Matrix :
  ********************

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,15.0,16.0,17.0,18.0,19.0,20.0,21.0,22.0,23.0,24.0,25.0,26.0,27.0,NaN
2,NaN,29.0,NaN,30.0,31.0,32.0,33.0,34.0,35.0,36.0,37.0,38.0,39.0,40.0,41.0,NaN
3,NaN,43.0,44.0,NaN,45.0,46.0,47.0,48.0,49.0,50.0,51.0,52.0,53.0,54.0,55.0,NaN
4,NaN,57.0,58.0,59.0,NaN,60.0,61.0,62.0,63.0,64.0,65.0,66.0,67.0,68.0,69.0,NaN
5,NaN,71.0,72.0,73.0,74.0,NaN,75.0,76.0,77.0,78.0,79.0,80.0,81.0,82.0,83.0,NaN
6,NaN,85.0,86.0,87.0,88.0,89.0,NaN,90.0,91.0,92.0,93.0,94.0,95.0,96.0,97.0,NaN
7,NaN,99.0,100.0,101.0,102.0,103.0,104.0,NaN,105.0,106.0,107.0,108.0,109.0,110.0,111.0,NaN
8,NaN,113.0,114.0,115.0,116.0,117.0,118.0,119.0,NaN,120.0,121.0,122.0,123.0,124.0,125.0,NaN
9,NaN,127.0,128.0,129.0,130.0,131.0,132.0,133.0,134.0,NaN,135.0,136.0,137.0,138.0,139.0,NaN
10,NaN,141.0,142.0,143.0,144.0,145.0,146.0,147.0,148.0,149.0,NaN,150.0,151.0,152.0,153.0,NaN
11,NaN,155.0,156.0,157.0,158.0,159.0,160.0,161.0,162.0,163.0,164.0,NaN,165.0,166.0,167.0,NaN
12,NaN,169.0,170.0,171.0,172.0,173.0,174.0,175.0,176.0,177.0,178.0,179.0,NaN,180.0,181.0,NaN
13,NaN,183.0,184.0,185.0,186.0,187.0,188.0,189.0,190.0,191.0,192.0,193.0,194.0,NaN,195.0,NaN
14,NaN,197.0,198.0,199.0,200.0,201.0,202.0,203.0,204.0,205.0,206.0,207.0,208.0,209.0,NaN,NaN
15,NaN,211.0,212.0,213.0,214.0,215.0,216.0,217.0,218.0,219.0,220.0,221.0,222.0,223.0,224.0,NaN

********************
 Probabilities  :
  ********************

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,0.0308,0.0308,0.0308,0.0308,0.0308,0.0308,0.0308,0.0308,0.0308,0.0308,0.0308,0.0308,0.0308,NaN
2,NaN,0.0071,NaN,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN
3,NaN,0.0071,0.0030,NaN,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN
4,NaN,0.0071,0.0030,0.0030,NaN,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN
5,NaN,0.0071,0.0030,0.0030,0.0030,NaN,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN
6,NaN,0.0071,0.0030,0.0030,0.0030,0.0030,NaN,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN
7,NaN,0.0071,0.0030,0.0030,0.0030,0.0030,0.0030,NaN,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN
8,NaN,0.0071,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN
9,NaN,0.0071,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN,0.0030,0.0030,0.0030,0.0030,0.0030,NaN
10,NaN,0.0071,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN,0.0030,0.0030,0.0030,0.0030,NaN
11,NaN,0.0071,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN,0.0030,0.0030,0.0030,NaN
12,NaN,0.0071,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN,0.0030,0.0030,NaN
13,NaN,0.0071,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN,0.0030,NaN
14,NaN,0.0071,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN,NaN
15,NaN,0.0071,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,0.0030,NaN

********************
 Huffman tree :
  ********************
{'0': {'0': {'0': {'0': {'0': {'0': {'0': {'0': '9-8', '1': '9-10'}, '1': {'0': '9-11', '1': '9-12'}}, '1': {'0': {'0': '9-13', '1': '9-14'}, '1': {'0': '10-2', '1': '10-3'}}}, '1': {'0': {'0': {'0': '10-4', '1': '10-5'}, '1': {'0': '10-6', '1': '10-7'}}, '1': {'0': {'0': '10-8', '1': '10-9'}, '1': {'0': '10-11', '1': '10-12'}}}}, '1': {'0': {'0': {'0': {'0': '10-13', '1': '10-14'}, '1': {'0': '11-2', '1': '11-3'}}, '1': {'0': {'0': '11-4', '1': '11-5'}, '1': {'0': '11-6', '1': '11-7'}}}, '1': {'0': {'0': {'0': '11-8', '1': '11-9'}, '1': {'0': '11-10', '1': '11-12'}}, '1': {'0': {'0': '11-13', '1': '11-14'}, '1': {'0': '12-2', '1': '12-3'}}}}}, '1': {'0': {'0': {'0': {'0': {'0': '12-4', '1': '12-5'}, '1': {'0': '12-6', '1': '12-7'}}, '1': {'0': {'0': '12-8', '1': '12-9'}, '1': {'0': '12-10', '1': '12-11'}}}, '1': {'0': {'0': {'0': '12-13', '1': '12-14'}, '1': {'0': '13-2', '1': '13-3'}}, '1': {'0': {'0': '13-4', '1': '13-5'}, '1': {'0': '13-6', '1': '13-7'}}}}, '1': {'0': {'0': {'0': {'0': '13-8', '1': '13-9'}, '1': {'0': '13-10', '1': '13-11'}}, '1': {'0': {'0': '13-12', '1': '13-14'}, '1': {'0': '14-2', '1': '14-3'}}}, '1': {'0': {'0': {'0': '14-4', '1': '14-5'}, '1': {'0': '14-6', '1': '14-7'}}, '1': {'0': {'0': '14-8', '1': '14-9'}, '1': {'0': '14-10', '1': '14-11'}}}}}}, '1': {'0': {'0': {'0': {'0': {'0': {'0': '14-12', '1': '14-13'}, '1': {'0': '15-2', '1': '15-3'}}, '1': {'0': {'0': '15-4', '1': '15-5'}, '1': {'0': '15-6', '1': '15-7'}}}, '1': {'0': {'0': {'0': '15-8', '1': '15-9'}, '1': {'0': '15-10', '1': '15-11'}}, '1': {'0': {'0': '15-12', '1': '15-13'}, '1': '2-1'}}}, '1': {'0': {'0': {'0': '3-1', '1': '4-1'}, '1': {'0': '5-1', '1': '6-1'}}, '1': {'0': {'0': '7-1', '1': '8-1'}, '1': {'0': '9-1', '1': '10-1'}}}}, '1': {'0': {'0': {'0': {'0': '11-1', '1': '12-1'}, '1': {'0': '13-1', '1': '14-1'}}, '1': '1-2'}, '1': {'0': '1-3', '1': '1-4'}}}}, '1': {'0': {'0': {'0': {'0': '1-5', '1': '1-6'}, '1': {'0': '1-7', '1': '1-8'}}, '1': {'0': {'0': '1-9', '1': '1-10'}, '1': {'0': '1-11', '1': '1-12'}}}, '1': {'0': {'0': {'0': '1-13', '1': '1-14'}, '1': {'0': {'0': {'0': '15-1', '1': {'0': '15-14', '1': {'0': '2-3', '1': '2-4'}}}, '1': {'0': {'0': {'0': '2-5', '1': '2-6'}, '1': {'0': '2-7', '1': '2-8'}}, '1': {'0': {'0': '2-9', '1': '2-10'}, '1': {'0': '2-11', '1': '2-12'}}}}, '1': {'0': {'0': {'0': {'0': '2-13', '1': '2-14'}, '1': {'0': '3-2', '1': '3-4'}}, '1': {'0': {'0': '3-5', '1': '3-6'}, '1': {'0': '3-7', '1': '3-8'}}}, '1': {'0': {'0': {'0': '3-9', '1': '3-10'}, '1': {'0': '3-11', '1': '3-12'}}, '1': {'0': {'0': '3-13', '1': '3-14'}, '1': {'0': '4-2', '1': '4-3'}}}}}}, '1': {'0': {'0': {'0': {'0': {'0': {'0': '4-5', '1': '4-6'}, '1': {'0': '4-7', '1': '4-8'}}, '1': {'0': {'0': '4-9', '1': '4-10'}, '1': {'0': '4-11', '1': '4-12'}}}, '1': {'0': {'0': {'0': '4-13', '1': '4-14'}, '1': {'0': '5-2', '1': '5-3'}}, '1': {'0': {'0': '5-4', '1': '5-6'}, '1': {'0': '5-7', '1': '5-8'}}}}, '1': {'0': {'0': {'0': {'0': '5-9', '1': '5-10'}, '1': {'0': '5-11', '1': '5-12'}}, '1': {'0': {'0': '5-13', '1': '5-14'}, '1': {'0': '6-2', '1': '6-3'}}}, '1': {'0': {'0': {'0': '6-4', '1': '6-5'}, '1': {'0': '6-7', '1': '6-8'}}, '1': {'0': {'0': '6-9', '1': '6-10'}, '1': {'0': '6-11', '1': '6-12'}}}}}, '1': {'0': {'0': {'0': {'0': {'0': '6-13', '1': '6-14'}, '1': {'0': '7-2', '1': '7-3'}}, '1': {'0': {'0': '7-4', '1': '7-5'}, '1': {'0': '7-6', '1': '7-8'}}}, '1': {'0': {'0': {'0': '7-9', '1': '7-10'}, '1': {'0': '7-11', '1': '7-12'}}, '1': {'0': {'0': '7-13', '1': '7-14'}, '1': {'0': '8-2', '1': '8-3'}}}}, '1': {'0': {'0': {'0': {'0': '8-4', '1': '8-5'}, '1': {'0': '8-6', '1': '8-7'}}, '1': {'0': {'0': '8-9', '1': '8-10'}, '1': {'0': '8-11', '1': '8-12'}}}, '1': {'0': {'0': {'0': '8-13', '1': '8-14'}, '1': {'0': '9-2', '1': '9-3'}}, '1': {'0': {'0': '9-4', '1': '9-5'}, '1': {'0': '9-6', '1': '9-7'}}}}}}}}}



********************
 Code dictionary :
  ********************
{'9-8': '00000000', '9-10': '00000001', '9-11': '00000010', '9-12': '00000011', '9-13': '00000100', '9-14': '00000101', '10-2': '00000110', '10-3': '00000111', '10-4': '00001000', '10-5': '00001001', '10-6': '00001010', '10-7': '00001011', '10-8': '00001100', '10-9': '00001101', '10-11': '00001110', '10-12': '00001111', '10-13': '00010000', '10-14': '00010001', '11-2': '00010010', '11-3': '00010011', '11-4': '00010100', '11-5': '00010101', '11-6': '00010110', '11-7': '00010111', '11-8': '00011000', '11-9': '00011001', '11-10': '00011010', '11-12': '00011011', '11-13': '00011100', '11-14': '00011101', '12-2': '00011110', '12-3': '00011111', '12-4': '00100000', '12-5': '00100001', '12-6': '00100010', '12-7': '00100011', '12-8': '00100100', '12-9': '00100101', '12-10': '00100110', '12-11': '00100111', '12-13': '00101000', '12-14': '00101001', '13-2': '00101010', '13-3': '00101011', '13-4': '00101100', '13-5': '00101101', '13-6': '00101110', '13-7': '00101111', '13-8': '00110000', '13-9': '00110001', '13-10': '00110010', '13-11': '00110011', '13-12': '00110100', '13-14': '00110101', '14-2': '00110110', '14-3': '00110111', '14-4': '00111000', '14-5': '00111001', '14-6': '00111010', '14-7': '00111011', '14-8': '00111100', '14-9': '00111101', '14-10': '00111110', '14-11': '00111111', '14-12': '01000000', '14-13': '01000001', '15-2': '01000010', '15-3': '01000011', '15-4': '01000100', '15-5': '01000101', '15-6': '01000110', '15-7': '01000111', '15-8': '01001000', '15-9': '01001001', '15-10': '01001010', '15-11': '01001011', '15-12': '01001100', '15-13': '01001101', '2-1': '0100111', '3-1': '0101000', '4-1': '0101001', '5-1': '0101010', '6-1': '0101011', '7-1': '0101100', '8-1': '0101101', '9-1': '0101110', '10-1': '0101111', '11-1': '0110000', '12-1': '0110001', '13-1': '0110010', '14-1': '0110011', '1-2': '01101', '1-3': '01110', '1-4': '01111', '1-5': '10000', '1-6': '10001', '1-7': '10010', '1-8': '10011', '1-9': '10100', '1-10': '10101', '1-11': '10110', '1-12': '10111', '1-13': '11000', '1-14': '11001', '15-1': '1101000', '15-14': '11010010', '2-3': '110100110', '2-4': '110100111', '2-5': '110101000', '2-6': '110101001', '2-7': '110101010', '2-8': '110101011', '2-9': '110101100', '2-10': '110101101', '2-11': '110101110', '2-12': '110101111', '2-13': '110110000', '2-14': '110110001', '3-2': '110110010', '3-4': '110110011', '3-5': '110110100', '3-6': '110110101', '3-7': '110110110', '3-8': '110110111', '3-9': '110111000', '3-10': '110111001', '3-11': '110111010', '3-12': '110111011', '3-13': '110111100', '3-14': '110111101', '4-2': '110111110', '4-3': '110111111', '4-5': '111000000', '4-6': '111000001', '4-7': '111000010', '4-8': '111000011', '4-9': '111000100', '4-10': '111000101', '4-11': '111000110', '4-12': '111000111', '4-13': '111001000', '4-14': '111001001', '5-2': '111001010', '5-3': '111001011', '5-4': '111001100', '5-6': '111001101', '5-7': '111001110', '5-8': '111001111', '5-9': '111010000', '5-10': '111010001', '5-11': '111010010', '5-12': '111010011', '5-13': '111010100', '5-14': '111010101', '6-2': '111010110', '6-3': '111010111', '6-4': '111011000', '6-5': '111011001', '6-7': '111011010', '6-8': '111011011', '6-9': '111011100', '6-10': '111011101', '6-11': '111011110', '6-12': '111011111', '6-13': '111100000', '6-14': '111100001', '7-2': '111100010', '7-3': '111100011', '7-4': '111100100', '7-5': '111100101', '7-6': '111100110', '7-8': '111100111', '7-9': '111101000', '7-10': '111101001', '7-11': '111101010', '7-12': '111101011', '7-13': '111101100', '7-14': '111101101', '8-2': '111101110', '8-3': '111101111', '8-4': '111110000', '8-5': '111110001', '8-6': '111110010', '8-7': '111110011', '8-9': '111110100', '8-10': '111110101', '8-11': '111110110', '8-12': '111110111', '8-13': '111111000', '8-14': '111111001', '9-2': '111111010', '9-3': '111111011', '9-4': '111111100', '9-5': '111111101', '9-6': '111111110', '9-7': '111111111'}



Leaf number : 782
Huffman code : 1605
Entropy : 6.922315145046944
Huffman Code length : 6.966272189349113